0.1/596 cc family sheet design individual family
neontribe/ARCVStore pull request #14
Opened 2017-12-12 16:31 UTC by alexalala

individual sheet 

https://trello.com/c/3exJIJFy/596-cc-family-sheet-design-individual-family

:octocat:

2017-12-13 09:19 UTC, charlesstrange2 requested changes
Change the Collector / Participant thing.

2017-12-13 09:19 UTC, charlesstrange2 commented on public/family.html
> +					<th>Participant Signature</th>
Change to "Collector Signature"

2017-12-13 11:44 UTC, alexalala commented
@charlesstrange2 all ready now, did something dumdum though and committed while on my vagrant box, do you want me to rewind the commits and re commit it all?

2017-12-14 09:53 UTC, charlesstrange2 approved these changes
Looks OK too!
:christmas_tree:

2017-12-14 11:02 UTC, merged