0.2/665 fuzzy search medium
neontribe/ARCVStore pull request #43
Opened 2018-01-16 12:10 UTC by charlesstrange2

2018-01-16 16:21 UTC, alexalala requested changes
Limited Laravel knowledge, but the bits I do understand I dont have a problem with! Other than the page I've commented on 👍  will approve when it's amended.

2018-01-16 16:21 UTC, alexalala commented on resources/views/service/index_registration.blade.php
> +                            <td>{{ $registration->family->rvid }}</td>
From prototyping, voucher entitlement is the second col in the div and then RV ID. As I've already changed this, could just remove the changes to this file?

2018-01-16 16:27 UTC, charlesstrange2 commented
Agreed, will amend.


On 16 January 2018 at 16:21, Alexandra Moore <notifications@github.com>
wrote:

> *@alexalala* requested changes on this pull request.
>
> Limited Laravel knowledge, but the bits I do understand I dont have a
> problem with! Other than the page I've commented on 👍 will approve when
> it's amended.
> ------------------------------
>
> In resources/views/service/index_registration.blade.php
> <https://github.com/neontribe/ARCVStore/pull/43#discussion_r161805011>:
>
> > @@ -40,7 +40,7 @@
>                      @foreach ($registrations as $registration)
>                          <tr>
>                              <td>{{ $registration->family->carers->first()->name }}</td>
> -                            <td>{{ $registration->cc_reference }}</td>
> +                            <td>{{ $registration->family->rvid }}</td>
>
> From prototyping, voucher entitlement is the second col in the div and
> then RV ID. As I've already changed this, could just remove the changes to
> this file?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/neontribe/ARCVStore/pull/43#pullrequestreview-89151549>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AX4I7Iuut0srhpH_8hSlrHGmPrsYYrA3ks5tLMyggaJpZM4RfrVb>
> .
>

2018-01-17 10:01 UTC, alexalala approved these changes
Beautiful! 🎊

2018-01-17 10:11 UTC, merged