0.2/709 tests to be added
neontribe/ARCVStore pull request #46
Opened 2018-01-18 15:15 UTC by alexalala

https://trello.com/c/At4TvLVe/709-tests-to-be-added

Had to remove some tests that were more browser tests, so just these 2 left :(

🍨

2018-01-18 17:19 UTC, charlesstrange2 requested changes

2018-01-18 17:19 UTC, charlesstrange2 commented on tests/Feature/RegistrationPageTest.php
> +            ->expectException(Error::class)
See If there's a specific exception, or try grabbing the exception message to test.

2018-01-19 13:47 UTC, alexalala commented on tests/Feature/RegistrationPageTest.php
> +            ->expectException(Error::class)
it wouldn't work with $this->expectException(InvalidArgumentException::class);, so I used the other approved method in the docs https://phpunit.de/manual/current/en/writing-tests-for-phpunit.html

2018-01-19 14:12 UTC, charlesstrange2 approved these changes

2018-01-19 14:32 UTC, merged